/**
 * Documentation checks: the license the app claims ships with it, and README / CHANGELOG / docs describe this
 * product as it is — no internal process notes, personal paths, struck-through feature lists, features the app
 * does not have, or references to files and dependencies that do not exist.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const ROOT = fileURLToPath(new URL('../../..', import.meta.url))
const read = (file: string): string => readFileSync(join(ROOT, file), 'utf8')
const DOCS = [
  'README.md',
  'CHANGELOG.md',
  ...readdirSync(join(ROOT, 'docs'))
    .filter((f) => f.endsWith('.md'))
    .map((f) => `docs/${f}`)
]
const pkg = JSON.parse(read('package.json')) as {
  license: string
  author: string
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
}
const packages = new Set([...Object.keys(pkg.dependencies ?? {}), ...Object.keys(pkg.devDependencies ?? {})])

/** `a/{b,c}.ts` → `a/b.ts`, `a/c.ts` (one level of braces is all the docs use). */
function expandBraces(path: string): string[] {
  const m = /\{([^{}]*)\}/.exec(path)
  if (!m) return [path]
  return m[1].split(',').flatMap((part) => expandBraces(path.slice(0, m.index) + part + path.slice(m.index + m[0].length)))
}

/** Paths the docs mention that are not repository files. */
const NOT_REPO_FILES = new Set([
  'src/Kernel.php', // a Symfony project's kernel (driver detection)
  'resources/sandbox' // generated by `npm run prepare:sandbox`
])

/** Repository paths a document refers to: `src/…` in backticks, or `// src/…` comments in code blocks. */
function referencedPaths(text: string): string[] {
  const found = new Set<string>()
  const re = /`((?:src|resources|tests|scripts|docs)\/[^`\s]+)`|^\s*\/\/ ((?:src|resources|tests|scripts|docs)\/\S+)/gm
  for (const m of text.matchAll(re)) {
    const path = (m[1] ?? m[2]).replace(/\/\*\*$/, '').replace(/\/$/, '')
    if (/[*<>…]/.test(path)) continue
    for (const p of expandBraces(path)) found.add(p)
  }
  return [...found]
}

describe('license and README', () => {
  it('has an MIT LICENSE carrying the copyright notice of the package author', () => {
    expect(pkg.license).toBe('MIT')
    const license = read('LICENSE')
    expect(license.startsWith('MIT License')).toBe(true)
    expect(license).toMatch(new RegExp(`Copyright \\(c\\) \\d{4} ${pkg.author}`))
    expect(license).toContain('The above copyright notice and this permission notice shall be included')
  })

  it('packages the LICENSE with the app (the About page refers to it)', () => {
    expect(read('electron-builder.yml')).toMatch(/extraResources:[\s\S]*- from: LICENSE\s+to: LICENSE/)
  })

  it('has a README that introduces Tinkerbox and links the docs and the license', () => {
    const readme = read('README.md')
    expect(readme.startsWith('# Tinkerbox\n')).toBe(true)
    for (const link of ['docs/ARCHITECTURE.md', 'docs/FEATURES.md', 'LICENSE']) expect(readme).toContain(`](${link})`)
  })
})

describe.each(DOCS)('%s', (file) => {
  const text = read(file)

  it('contains no internal process notes, personal paths or struck-through items', () => {
    expect(text).not.toMatch(/SCOPE CHANGE|product owner|owned by|never edit files|do not run `npm install`|\bSTUBS?\b/i)
    expect(text).not.toMatch(/\/Users\/(?!me\/)[^/\s]+\//) // examples use /Users/me/…
    expect(text).not.toContain('~~')
  })

  it('does not describe features the app does not have', () => {
    for (const term of [/\bssh2\b/, /\bMCP\b/, /\bForge\b/, /\bVapor\b/, /Laravel Cloud/, /\bkubectl\b/, /\bAI\b/, /\bCHAT\b/, /\bR6\b/]) {
      expect(text, `${file} mentions ${term}`).not.toMatch(term)
    }
  })

  it('refers only to files that exist', () => {
    const missing = referencedPaths(text).filter((p) => !NOT_REPO_FILES.has(p) && !existsSync(join(ROOT, p)))
    expect(missing).toEqual([])
  })
})

describe('docs/ARCHITECTURE.md', () => {
  const text = read('docs/ARCHITECTURE.md')

  it('refers to many repository files (the path check is not vacuous)', () => {
    expect(referencedPaths(text).length).toBeGreaterThan(40)
  })

  it('lists only dependencies that package.json has', () => {
    const stack = /^\*\*(Electron .*)\*\*$/m.exec(text)?.[1]
    expect(stack).toBeDefined()
    const aliases: Record<string, string> = { tailwind: 'tailwindcss', monaco: 'monaco-editor' }
    for (const part of stack!.split(/ · | \+ /)) {
      const name = part.trim().split(/\s/)[0].toLowerCase()
      expect(packages.has(aliases[name] ?? name), `stack entry "${part}"`).toBe(true)
    }
    const deps = /^Dependencies:([\s\S]*?)\n\n/m.exec(text)?.[1] ?? ''
    const named = [...deps.matchAll(/`([^`]+)`/g)].map((m) => m[1])
    expect(named.length).toBeGreaterThan(5)
    for (const name of named) expect(packages.has(name), `dependency ${name}`).toBe(true)
  })

  it('documents only the transports that exist, with remote ones as a roadmap item', () => {
    const transports = readdirSync(join(ROOT, 'src/main/execution')).filter((f) => /Transport\.ts$/.test(f))
    expect(transports).toEqual(['localTransport.ts'])
    expect(text).toContain('**Roadmap:** remote transports (SSH, Docker, …) via the Transport extension point (see §2.1).')
    expect(text.match(/\bSSH\b/g)?.length).toBe(2) // the roadmap note and the extension point paragraph
  })
})

describe('docs/RENDERER.md', () => {
  it('lists modal components that exist', () => {
    const rows = [...read('docs/RENDERER.md').matchAll(/^\| `\w+` \| ([\w/]+\.vue) \|/gm)].map((m) => m[1])
    expect(rows.length).toBeGreaterThan(10)
    const missing = rows.filter((file) => !existsSync(join(ROOT, 'src/renderer/src/components', file)))
    expect(missing).toEqual([])
  })
})

describe('docs/FEATURES.md', () => {
  const text = read('docs/FEATURES.md')
  const items = text.split('\n').filter((l) => l.startsWith('- ['))
  const areas = new Set([...read('docs/ARCHITECTURE.md').matchAll(/^\| \*\*([A-Z]\d) /gm)].map((m) => m[1]))

  it('has a checkbox, an id and a known area code on every item', () => {
    expect(items.length).toBeGreaterThan(60)
    for (const item of items) {
      expect(item, item).toMatch(/^- \[(x| )\] F\d{2,3} /)
      const codes = [...item.matchAll(/\[([A-Z]\d(?:, [A-Z]\d)*)\]/g)].flatMap((m) => m[1].split(', '))
      expect(codes.length, item).toBeGreaterThan(0)
      for (const code of codes) expect(areas.has(code), `${code} in ${item}`).toBe(true)
    }
  })

  it('says why an item is not checked', () => {
    for (const item of items.filter((l) => l.startsWith('- [ ]'))) expect(item, item).toMatch(/ — \S/)
  })

  it('describes Xdebug debugging as the per-project toggle the app has', () => {
    expect(items.find((l) => l.includes(' F14 '))).toMatch(/^- \[x\] F14 Xdebug step debugging toggle per project /)
  })
})
