/** Static completion data: PHP keywords and snippets. */

export interface PhpSnippet {
  label: string
  detail: string
  /** Monaco snippet syntax (`$` escaped as `\$`). */
  body: string
}

export const PHP_SNIPPETS: readonly PhpSnippet[] = [
  { label: 'foreach', detail: 'foreach ($items as $item)', body: 'foreach (${1:\\$items} as ${2:\\$item}) {\n\t$0\n}' },
  { label: 'foreach =>', detail: 'foreach ($items as $key => $value)', body: 'foreach (${1:\\$items} as ${2:\\$key} => ${3:\\$value}) {\n\t$0\n}' },
  { label: 'fn', detail: 'Arrow function', body: 'fn (${1:\\$x}) => ${0:\\$x}' },
  { label: 'function', detail: 'Closure', body: 'function (${1}) {\n\t$0\n}' },
  { label: 'function name', detail: 'Function declaration', body: 'function ${1:name}(${2}): ${3:mixed}\n{\n\t$0\n}' },
  { label: 'match', detail: 'match expression', body: 'match (${1:\\$value}) {\n\t${2:1} => ${3:\'one\'},\n\tdefault => ${0:null},\n}' },
  { label: 'if', detail: 'if statement', body: 'if (${1:\\$condition}) {\n\t$0\n}' },
  { label: 'if else', detail: 'if / else', body: 'if (${1:\\$condition}) {\n\t$2\n} else {\n\t$0\n}' },
  { label: 'for', detail: 'for loop', body: 'for (\\$${1:i} = 0; \\$${1:i} < ${2:10}; \\$${1:i}++) {\n\t$0\n}' },
  { label: 'while', detail: 'while loop', body: 'while (${1:\\$condition}) {\n\t$0\n}' },
  { label: 'do while', detail: 'do / while loop', body: 'do {\n\t$0\n} while (${1:\\$condition});' },
  { label: 'switch', detail: 'switch statement', body: 'switch (${1:\\$value}) {\n\tcase ${2:1}:\n\t\t$3\n\t\tbreak;\n\tdefault:\n\t\t$0\n}' },
  { label: 'try', detail: 'try / catch', body: 'try {\n\t$1\n} catch (${2:\\\\Throwable} \\$${3:e}) {\n\t$0\n}' },
  { label: 'try finally', detail: 'try / catch / finally', body: 'try {\n\t$1\n} catch (${2:\\\\Throwable} \\$${3:e}) {\n\t$4\n} finally {\n\t$0\n}' },
  { label: 'class', detail: 'Class declaration', body: 'class ${1:Name}\n{\n\tpublic function __construct(${2})\n\t{\n\t\t$0\n\t}\n}' },
  { label: 'enum', detail: 'Backed enum', body: "enum ${1:Status}: string\n{\n\tcase ${2:Active} = '${3:active}';\n$0\n}" },
  { label: 'interface', detail: 'Interface declaration', body: 'interface ${1:Name}\n{\n\t$0\n}' },
  { label: 'collect', detail: 'collect([...])', body: 'collect([${1}])$0' },
  { label: 'dump', detail: 'dump($value)', body: 'dump(${1:\\$value});$0' },
  { label: 'dd', detail: 'dd($value)', body: 'dd(${1:\\$value});$0' },
  { label: 'benchmark', detail: 'Measure a closure with hrtime()', body: '\\$start = hrtime(true);\n$0\n(hrtime(true) - \\$start) / 1e6; //? ms' }
]

/** Keywords offered by completion (snippets cover the block statements). */
export const PHP_KEYWORDS: readonly string[] = [
  'abstract',
  'and',
  'array',
  'as',
  'break',
  'callable',
  'case',
  'catch',
  'class',
  'clone',
  'const',
  'continue',
  'declare',
  'default',
  'do',
  'echo',
  'else',
  'elseif',
  'empty',
  'enum',
  'exit',
  'extends',
  'false',
  'final',
  'finally',
  'fn',
  'for',
  'foreach',
  'function',
  'global',
  'goto',
  'if',
  'implements',
  'include',
  'include_once',
  'instanceof',
  'insteadof',
  'interface',
  'isset',
  'list',
  'match',
  'namespace',
  'new',
  'null',
  'or',
  'parent',
  'print',
  'private',
  'protected',
  'public',
  'readonly',
  'require',
  'require_once',
  'return',
  'self',
  'static',
  'switch',
  'throw',
  'trait',
  'true',
  'try',
  'unset',
  'use',
  'var',
  'while',
  'xor',
  'yield',
  'yield from',
  'int',
  'float',
  'string',
  'bool',
  'iterable',
  'mixed',
  'void',
  'never',
  'object'
]

/** Always-available variables. */
export const PHP_SUPERGLOBALS: readonly string[] = ['$GLOBALS', '$_SERVER', '$_GET', '$_POST', '$_FILES', '$_REQUEST', '$_SESSION', '$_ENV', '$_COOKIE', '$argv', '$argc']
